apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42-playground-deployment
  namespace: dev
  labels:
    app: wil42-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil42-playground
  template:
    metadata:
      labels:
        app: wil42-playground
    spec:
      containers:
      - name: wil42-playground
        image: wil42/playground:v1
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: wil42-playground-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: wil42-playground
  ports:
  - port: 8888
    targetPort: 8888