Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  config.vm.define "ymoriS" do |srv|
    srv.vm.hostname = "ymoriS"
    srv.vm.network "private_network", ip: "192.168.56.110"
    srv.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    srv.vm.provision "shell", path: "scripts/srv.sh"
    srv.vm.provision "shell", inline: <<-SHELL
      kubectl apply -f /vagrant/confs/app1-deployment.yaml
      kubectl apply -f /vagrant/confs/app2-deployment.yaml
      kubectl apply -f /vagrant/confs/app3-deployment.yaml
      kubectl apply -f /vagrant/confs/app1-config.yaml
      kubectl apply -f /vagrant/confs/app2-config.yaml
      kubectl apply -f /vagrant/confs/app3-config.yaml
      kubectl apply -f /vagrant/confs/app-ingress.yaml
    SHELL
  end
end
