apiVersion: v1
kind: Secret
metadata:
  name: gitlab-https-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: http://localhost:8880/root/42iot.git
  password: gldt-QzNP36k1cNVBRJrxAUGy
  username: argocd