apiVersion: v1
kind: Secret
metadata:
  name: gitlab-https-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: http://gitlab-webservice-default.gitlab.svc.cluster.local:8080/root/iot.git
  password: gldt-RC-2-zBVi3qcJBDwFqPw
  username: argocd
