apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  # url: http://gitlab-webservice-default.gitlab.svc.cluster.local:8080/root/42iot.git
  url: https://gitlab.com/ymori06/42-ymori-Inception-of-Things-ArgoCD.git
  username: argocd 
  password: gldt-Jfy7k_cUgXPqgQVsYj4X