Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  config.vm.define "ymoriS" do |cplane|
    cplane.vm.hostname = "ymoriS"
    cplane.vm.network "private_network", ip: "192.168.56.110"
    cplane.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    cplane.vm.provision "shell", path: "scripts/cplane.sh"
  end

  config.vm.define "ymoriSW" do |worker|
    worker.vm.hostname = "ymoriSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end